server:
  port: 8081
spring:
  redis:
    port: 6379
    password: Dhr363345462
    # 数据库索引（0 - 15）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    # lettuce 参数
    client-name: jedis
    jedis:
      pool:
        max-active: 8
        max-wait: 2000
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000
    host: 35.78.81.22
